---
title: "mobile"
author: "Li Zongzhang"
date: "`r Sys.Date()`"
format:
  html:
    code-fold: true      
    code-summary: "code" 
    code-tools: true    
    toc: true
    number-sections: true
---

# 数据和变量

数据来源：mobile.xlsx

样本容量：142

laptop: 笔记本电脑价格(元)

cost: 月生活费(元)

mobile: 手机价格(元)

mobile: 笔记本电脑使用时长(月)

gender: 性别

demand_type: 需求类型(性能-performance/轻量-lite)

brand_prefer: 品牌偏好(高端设计-premium/主流商务-mainstream/专业游戏-gaming/高性价比-value)


```{r}
#| message: false
#| warning: false
#| include: false
library(tidyverse)
library(knitr)
library(flextable)
```


```{r}
#| message: false
#| warning: false
#| include: false
library(readxl)
df <- read_excel("data/mobile.xlsx")
```


# 描述性统计分析

## 定量变量

```{r}
#| echo: true
#| #| message: false
#| warning: false

library(modelsummary)
datasummary(laptop + cost + mobile + usage_month ~ 
                     N + Mean + SD + Median + Min + Max, 
                   data = df, 
                   fmt = 3, 
                   output = 'flextable') %>%
  theme_apa() %>%              
  autofit() %>%               
  font(fontname = "Times New Roman", part = "all")

```

---

## 定性变量


```{r}
#| echo: true
#| #| message: false
#| warning: false

datasummary(gender + demand_type + brand_prefer ~ 
            N + Percent() + laptop * (Mean + Median + SD + Min + Max), 
            data = df, 
            fmt = 2, 
            output = 'flextable') %>%
  theme_apa() %>%
  autofit() %>%
  font(fontname = "Times New Roman", part = "all")
```


# 回归分析

## Model 1 

```{r}
#| echo: true
#| message: false
#| warning: false
#| label: tbl1-reg-results
#| tbl-cap: "Model 1 Regression Analysis"

library(broom)
m1 <- lm(laptop ~ cost + mobile + usage_month, data = df)

models_list <- list("Model 1" = m1)

modelsummary(
  list("Model 1" = m1), 
  fmt = 3, 
  stars = TRUE, 
  gof_omit = 'AIC|BIC|Log.Lik|F|statistic', 
  output = "flextable"
) %>% 
  theme_apa() %>%
  fontsize(size = 18, part = "all") %>%      
  padding(padding = 5, part = "all") %>%
  autofit() %>%
  font(fontname = "Times New Roman", part = "all")


```


```{r}
#| results: asis
#| echo: false
#| message: false
#| warning: false

library(equatiomatic)

extract_eq(m1, use_coefs = TRUE, coef_digits = 3, fix_names = FALSE)


```
---

## Model 2.1

```{r}
#| echo: true
#| #| message: false
#| warning: false
#| label: tbl2-reg-results
#| tbl-cap: "Model 2 Regression Analysis"

library(broom)
m2 <- lm(log(laptop) ~ log(cost) + log(mobile) + usage_month, data = df)

models_list <- list("Model 2 (Y=log(laptop))" = m2)

modelsummary(
  models_list, 
  fmt = 3, 
  stars = TRUE,  
  gof_omit = 'AIC|BIC|Log.Lik|F|statistic', 
  output = "flextable"
) %>% 
  theme_apa() %>% 
  autofit() %>%
  font(fontname = "Times New Roman", part = "all")


```


```{r}
#| results: asis
#| echo: false
#| message: false
#| warning: false

library(equatiomatic)

extract_eq(m2, 
           use_coefs = TRUE, 
           coef_digits = 3,          
           fix_names = TRUE)


```


## Model 2.2

```{r}
#| echo: true
#| #| message: false
#| warning: false
#| label: tbl2.2-reg-results
#| tbl-cap: "Model 2 Regression Analysis"

library(broom)
m2.2 <- lm(log(laptop) ~ log(cost) + log(mobile) + usage_month + gender + 
     gender:log(mobile), data = df)

models_list <- list("Model 2 (Y=log(laptop))" = m2.2)

modelsummary(
  models_list, 
  fmt = 3, 
  stars = TRUE,  
  gof_omit = 'AIC|BIC|Log.Lik|F|statistic', 
  output = "flextable"
) %>% 
  theme_apa() %>% 
  autofit() %>%
  font(fontname = "Times New Roman", part = "all")


```


```{r}
#| results: asis
#| echo: false
#| message: false
#| warning: false

library(equatiomatic)

extract_eq(m2.2, 
           use_coefs = TRUE, 
           coef_digits = 3, 
           wrap = TRUE,
           fix_names = TRUE)


```


---

## Model 3

```{r}
#| echo: true
#| #| message: false
#| warning: false
#| label: tbl3-reg-results
#| tbl-cap: "Regression Analysis"
m3 <- lm(laptop ~ cost + mobile + usage_month + gender, data = df)

models_list <- list("Model 3" = m3)

modelsummary(
  models_list, 
  fmt = 3, 
  stars = TRUE,  
  gof_omit = 'AIC|BIC|Log.Lik|F|statistic', 
  output = "flextable"
) %>% 
  theme_apa() %>% 
  autofit() %>%
  font(fontname = "Times New Roman", part = "all")

```


```{r}
#| results: asis
#| echo: false
#| message: false
#| warning: false

library(equatiomatic)

extract_eq(m3, 
           use_coefs = TRUE, 
           coef_digits = 3,          
           fix_names = TRUE)


```

---

## Model 4

```{r}
#| echo: true
#| #| message: false
#| warning: false
#| label: tbl4-reg-results
#| tbl-cap: "Regression Analysis"
m4 <- lm(log(laptop) ~ log(cost) + log(mobile) + 
           usage_month + 
           gender + demand_type + brand_prefer , data = df)

models_list <- list("Model 4" = m4)

modelsummary(
  models_list, 
  fmt = 3, 
  stars = TRUE,  
  gof_omit = 'AIC|BIC|Log.Lik|F|statistic', 
  output = "flextable"
) %>% 
  theme_apa() %>% 
  autofit() %>%
  font(fontname = "Times New Roman", part = "all")

```


```{r}
#| results: asis
#| echo: false
#| message: false
#| warning: false

library(equatiomatic)

extract_eq(m4, 
           use_coefs = TRUE, 
           coef_digits = 4,          
           fix_names = TRUE,
           wrap = TRUE)


```

